package fr.hybridetv.drunly.init;

import java.util.ArrayList;
import java.util.List;

import fr.hybridetv.drunly.*;
import fr.hybridetv.drunly.acier.Acier;
import fr.hybridetv.drunly.bases.ItemBase;
import fr.hybridetv.drunly.bases.ItemFoodBase;
import fr.hybridetv.drunly.boost.BoostBoots;
import fr.hybridetv.drunly.boost.BoostChestplate;
import fr.hybridetv.drunly.boost.BoostHelmet;
import fr.hybridetv.drunly.boost.BoostLeggings;
import fr.hybridetv.drunly.bow.CobaltBow;
import fr.hybridetv.drunly.bow.EmeraldBow;
import fr.hybridetv.drunly.bow.RubisBow;
import fr.hybridetv.drunly.christmasupdate.TurtleHelmet;
import fr.hybridetv.drunly.christmasupdate.XpBerry;
import fr.hybridetv.drunly.cobalt.CobaltAxe;
import fr.hybridetv.drunly.cobalt.CobaltBoots;
import fr.hybridetv.drunly.cobalt.CobaltChestplate;
import fr.hybridetv.drunly.cobalt.CobaltHelmet;
import fr.hybridetv.drunly.cobalt.CobaltIngot;
import fr.hybridetv.drunly.cobalt.CobaltLeggings;
import fr.hybridetv.drunly.cobalt.CobaltPickaxe;
import fr.hybridetv.drunly.cobalt.CobaltShovel;
import fr.hybridetv.drunly.cobalt.CobaltSword;
import fr.hybridetv.drunly.cobalt.DrunlykPickaxe;
import fr.hybridetv.drunly.drunlyk.DrunlykAxe;
import fr.hybridetv.drunly.drunlyk.DrunlykBoots;
import fr.hybridetv.drunly.drunlyk.DrunlykChestplate;
import fr.hybridetv.drunly.drunlyk.DrunlykHammer;
import fr.hybridetv.drunly.drunlyk.DrunlykHelmet;
import fr.hybridetv.drunly.drunlyk.DrunlykIngot;
import fr.hybridetv.drunly.drunlyk.DrunlykLeggings;
import fr.hybridetv.drunly.drunlyk.DrunlykPowder;
import fr.hybridetv.drunly.drunlyk.DrunlykShovel;
import fr.hybridetv.drunly.drunlyk.DrunlykSword;
import fr.hybridetv.drunly.emerald.EmeraldAxe;
import fr.hybridetv.drunly.emerald.EmeraldBoots;
import fr.hybridetv.drunly.emerald.EmeraldChestplate;
import fr.hybridetv.drunly.emerald.EmeraldHelmet;
import fr.hybridetv.drunly.emerald.EmeraldLeggings;
import fr.hybridetv.drunly.emerald.EmeraldPickaxe;
import fr.hybridetv.drunly.emerald.EmeraldShovel;
import fr.hybridetv.drunly.emerald.EmeraldSword;
import fr.hybridetv.drunly.explosives.Dynamite;
import fr.hybridetv.drunly.explosives.HardenedDynamite;
import fr.hybridetv.drunly.farm.CarrotSeedPlanter;
import fr.hybridetv.drunly.farm.Cerise;
import fr.hybridetv.drunly.farm.CitronSeedPlanter;
import fr.hybridetv.drunly.farm.CourgetteSeedPlanter;
import fr.hybridetv.drunly.farm.EmptySeedPlanter;
import fr.hybridetv.drunly.farm.ErableFood;
import fr.hybridetv.drunly.farm.ErableSeedPlanter;
import fr.hybridetv.drunly.farm.FarmingModifier;
import fr.hybridetv.drunly.farm.FraiseFood;
import fr.hybridetv.drunly.farm.Grenade;
import fr.hybridetv.drunly.farm.KiwiFood;
import fr.hybridetv.drunly.farm.KiwiSeedPlanter;
import fr.hybridetv.drunly.farm.MagicalRecolter;
import fr.hybridetv.drunly.farm.MyrtilleSeedPlanter;
import fr.hybridetv.drunly.farm.PotatoSeedPlanter;
import fr.hybridetv.drunly.farm.RizSeedPlanter;
import fr.hybridetv.drunly.farm.SaladeSeedPlanter;
import fr.hybridetv.drunly.farm.StrawberrySeedPlanter;
import fr.hybridetv.drunly.farm.Tomato;
import fr.hybridetv.drunly.farm.TomatoSeedPlanter;
import fr.hybridetv.drunly.farm.TrefleFood;
import fr.hybridetv.drunly.farm.TrefleSeedPlanter;
import fr.hybridetv.drunly.food.ItemCeriseIce;
import fr.hybridetv.drunly.food.ItemCitronIce;
import fr.hybridetv.drunly.food.ItemFraiseIce;
import fr.hybridetv.drunly.food.ItemJoin;
import fr.hybridetv.drunly.food.ItemKiwiIce;
import fr.hybridetv.drunly.food.ItemMyrtilleIce;
import fr.hybridetv.drunly.food.Risotto;
import fr.hybridetv.drunly.food.SaladeTomate;
import fr.hybridetv.drunly.hammers.CobaltHammer;
import fr.hybridetv.drunly.hammers.DiamondHammer;
import fr.hybridetv.drunly.hammers.EmeraldHammer;
import fr.hybridetv.drunly.hammers.GoldHammer;
import fr.hybridetv.drunly.hammers.IronHammer;
import fr.hybridetv.drunly.hammers.RubisHammer;
import fr.hybridetv.drunly.hammers.StoneHammer;
import fr.hybridetv.drunly.hematite.HematiteAxe;
import fr.hybridetv.drunly.hematite.HematiteBoots;
import fr.hybridetv.drunly.hematite.HematiteChestplate;
import fr.hybridetv.drunly.hematite.HematiteHammer;
import fr.hybridetv.drunly.hematite.HematiteHelmet;
import fr.hybridetv.drunly.hematite.HematiteIngot;
import fr.hybridetv.drunly.hematite.HematiteLeggings;
import fr.hybridetv.drunly.hematite.HematitePickaxe;
import fr.hybridetv.drunly.hematite.HematiteShovel;
import fr.hybridetv.drunly.hematite.HematiteSword;
import fr.hybridetv.drunly.hoe.CobaltHoe;
import fr.hybridetv.drunly.hoe.DrunlykHoe;
import fr.hybridetv.drunly.hoe.EmeraldHoe;
import fr.hybridetv.drunly.hoe.HematiteHoe;
import fr.hybridetv.drunly.hoe.RubisHoe;
import fr.hybridetv.drunly.rubis.RubisAxe;
import fr.hybridetv.drunly.rubis.RubisBoots;
import fr.hybridetv.drunly.rubis.RubisChestplate;
import fr.hybridetv.drunly.rubis.RubisHelmet;
import fr.hybridetv.drunly.rubis.RubisIngot;
import fr.hybridetv.drunly.rubis.RubisLeggings;
import fr.hybridetv.drunly.rubis.RubisPickaxe;
import fr.hybridetv.drunly.rubis.RubisShovel;
import fr.hybridetv.drunly.rubis.RubisSword;
import fr.hybridetv.drunly.uranium.ItemUraniumIngot;
import fr.hybridetv.drunly.items.*;
import fr.hybridetv.drunly.potions.ErablePotion;
import fr.hybridetv.drunly.rings.ItemDrunlykRing;
import fr.hybridetv.drunly.rings.ItemHematiteRing;
import net.minecraft.client.renderer.block.model.ModelResourceLocation;
import net.minecraft.init.Blocks;
import net.minecraft.init.SoundEvents;
import net.minecraft.inventory.EntityEquipmentSlot;
import net.minecraft.item.Item;
import net.minecraft.item.Item.ToolMaterial;
import net.minecraft.item.ItemArmor.ArmorMaterial;
import net.minecraft.item.ItemSeeds;
import net.minecraftforge.client.event.ModelRegistryEvent;
import net.minecraftforge.client.model.ModelLoader;
import net.minecraftforge.common.util.EnumHelper;
import net.minecraftforge.event.RegistryEvent;
import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.fml.common.eventhandler.SubscribeEvent;

@Mod.EventBusSubscriber(modid=References.MODID)

public class ItemMod {
	public static final List<Item> ITEMS = new ArrayList<Item>();
	public static ToolMaterial toolstonehammer = EnumHelper.addToolMaterial("toolstonehammer", 3, 399, 3.0F, 4.5F, 25);
	public static ToolMaterial toolironhammer = EnumHelper.addToolMaterial("toolironhammer", 3, 599, 4.0F, 4.5F, 25);
	public static ToolMaterial toolgoldhammer = EnumHelper.addToolMaterial("toolgoldhammer", 3, 799, 6.0F, 4.5F, 25);
	public static ToolMaterial tooldiamondhammer = EnumHelper.addToolMaterial("tooldiamondhammer", 1, 1199, 8.0F, 4.5F, 25);
	public static ToolMaterial toolseedplanter = EnumHelper.addToolMaterial("toolseedplanter", 1, 99, 4.0F, 4.5F, 10);
	public static final ArmorMaterial emeraldarmor = EnumHelper.addArmorMaterial("emeraldarmor", References.MODID + ":emeraldarmor", 80, new int[] {4, 5, 5, 4}, 10, SoundEvents.ITEM_ARMOR_EQUIP_DIAMOND, 3.0F);
	public static ToolMaterial toolemerald = EnumHelper.addToolMaterial("toolemerald", 4, 1799, 12.0F, 10.0F, 15);	
	public static final ArmorMaterial rubisarmor = EnumHelper.addArmorMaterial("rubisarmor", References.MODID + ":rubisarmor", 130, new int[] {4, 6, 6, 4}, 20, SoundEvents.ITEM_ARMOR_EQUIP_DIAMOND, 3.0F);
	public static ToolMaterial toolrubis = EnumHelper.addToolMaterial("rubisarmor", 5, 2499, 15.0F, 14.0F, 25);
	public static final ArmorMaterial cobaltarmor = EnumHelper.addArmorMaterial("cobaltarmor", References.MODID + ":cobaltarmor", 170, new int[] {5, 7, 7, 5}, 15, SoundEvents.ITEM_ARMOR_EQUIP_DIAMOND, 3.0F);
	public static ToolMaterial toolcobalt = EnumHelper.addToolMaterial("toolcobalt", 5, 3999, 20.0F, 19.0F, 25);
	public static ToolMaterial toolhardened = EnumHelper.addToolMaterial("toolhardened", 13000, 99, 6000.0F, 10.0F, 1);
	public static final ArmorMaterial drunlykarmor = EnumHelper.addArmorMaterial("drunlykarmor", References.MODID + ":drunlykarmor", 190, new int[] {6, 8, 8, 6}, 20, SoundEvents.ITEM_ARMOR_EQUIP_DIAMOND, 3.0F);
	public static ToolMaterial tooldrunlyk = EnumHelper.addToolMaterial("tolldrunlyk", 5, 4499, 25.0F, 25.0F, 25);
	public static final ArmorMaterial hematitearmor = EnumHelper.addArmorMaterial("hematitearmor", References.MODID + ":hematitearmor", 220, new int[] {7, 8, 8, 7}, 20, SoundEvents.ITEM_ARMOR_EQUIP_DIAMOND, 3.0F);
	public static ToolMaterial toolhematite = EnumHelper.addToolMaterial("toolhematite", 5, 5999, 30.0F, 31.0F, 25);
	public static ToolMaterial tooladmin = EnumHelper.addToolMaterial("tooladmin", 5, 8999, 500.0F, 500.0F, 25);
	public static ToolMaterial toolmulti = EnumHelper.addToolMaterial("toolmulti", 5, 4999, 25.0F, 31.0F, 20);
	public static final ArmorMaterial boostarmor = EnumHelper.addArmorMaterial("boostarmor", References.MODID + ":boostarmor", 190, new int[] {6, 8, 8, 6}, 20, SoundEvents.ITEM_ARMOR_EQUIP_DIAMOND, 3.0F);
	public static Item admin_sword;
	public static Item drunlyk_helmet;
	public static Item drunlyk_chestplate;
	public static Item drunlyk_leggings;
	public static Item drunlyk_boots;
	public static Item drunlyk_sword;
	public static Item drunlyk_pickaxe;
	public static Item drunlyk_axe;
	public static Item drunlyk_shovel;
	public static Item hematite_helmet;
	public static Item hematite_chestplate;
	public static Item hematite_leggings;
	public static Item hematite_boots;
	public static Item hematite_sword;
	public static Item hematite_pickaxe;
	public static Item hematite_axe;
	public static Item hematite_shovel;
	public static Item hematite_ingot;
	public static Item hematite_hammer;
	public static Item cobalt_hoe;
	public static Item emerald_hoe;
	public static Item drunlyk_hoe;
	public static Item hematite_hoe;
	public static Item vodka;
	public static Item coins;
	public static Item acier;
	public static Item beer;
	public static Item money;
	public static Item dynamite;
	public static Item hardened_dynamite;
	public static Item emerald_helmet;
	public static Item emerald_chestplate;
	public static Item emerald_leggings;
	public static Item emerald_boots;
	public static Item emerald_sword;
	public static Item emerald_pickaxe;
	public static Item emerald_axe;
	public static Item emerald_shovel;
	public static Item rubis_helmet;
	public static Item rubis_chestplate;
	public static Item rubis_leggings;
	public static Item rubis_boots;
	public static Item rubis_sword;
	public static Item rubis_pickaxe;
	public static Item rubis_axe;
	public static Item rubis_shovel;
	public static Item rubis_ingot;
	public static Item rubis_apple;
	public static Item cobalt_helmet;
	public static Item cobalt_chestplate;
	public static Item cobalt_leggings;
	public static Item cobalt_boots;
	public static Item cobalt_sword;
	public static Item cobalt_pickaxe;
	public static Item cobalt_axe;
	public static Item cobalt_shovel;
	public static Item cobalt_ingot;
	public static Item cobalt_apple; 
	public static Item hardened_pickaxe;
	public static Item fraise_seed;
	public static Item fraise;
	public static Item erable_seed;
	public static Item erable;
	public static Item kiwi_seed;
	public static Item kiwi;
	public static Item trefle_seed;
	public static Item trefle;
	public static Item uranium_ingot;
	public static Item fried_egg;
	public static Item stone_hammer;
	public static Item iron_hammer;
	public static Item gold_hammer;
	public static Item diamond_hammer;
	public static Item fromage;
	public static Item emerald_hammer;
	public static Item rubis_hammer;
	public static Item cobalt_hammer;
	public static Item rubis_hoe;
	public static Item magical_recolter;
	public static Item drunlyk_ingot;
	public static Item drunlyk_powder;
	public static Item empty_modifier;
	public static Item potato_modifier;
	public static Item carrot_modifier;
	public static Item strawberry_modifier;
	public static Item kiwi_modifier;
	public static Item erable_modifier;
	public static Item trefle_modifier;
	public static Item empty_seed_planter;
	public static Item potato_seed_planter;
	public static Item carrot_seed_planter;
	public static Item strawberry_seed_planter;
	public static Item kiwi_seed_planter;
	public static Item erable_seed_planter;
	public static Item trefle_seed_planter;
	public static Item erable_potion;
	public static Item hardened_coal;
	public static Item gold_stick;
	public static Item tomato_seed;
	public static Item tomato;
	public static Item myrtille;
	public static Item myrtille_seed;
	public static Item citron;
	public static Item citron_seed;
	public static Item salade;
	public static Item salade_seed;
	public static Item riz;
	public static Item riz_seed;
	public static Item cerise;
	public static Item grenade;
	public static Item courgette;
	public static Item courgette_seed;
	public static Item drunlyk_hammer;
	public static Item hardened_briquet;
	public static Item risotto;
	public static Item salade_tomate;
	public static Item tomato_modifier;
	public static Item tomato_seed_planter;
	public static Item courgette_modifier;
	public static Item courgette_seed_planter;
	public static Item myrtille_modifier;
	public static Item myrtille_seed_planter;
	public static Item citron_modifier;
	public static Item citron_seed_planter;
	public static Item salade_modifier;
	public static Item salade_seed_planter;
	public static Item riz_modifier;
	public static Item riz_seed_planter;
	public static Item emerald_bow;
	public static Item rubis_bow;
	public static Item cobalt_bow;
	public static Item citron_ice;
	public static Item myrtille_ice;
	public static Item cerise_ice;
	public static Item kiwi_ice;
	public static Item fraise_ice;
	public static Item drunlyk_ring;
	public static Item hematite_ring;
	public static Item key;
	public static Item farmtool;
	public static Item boost_helmet;
	public static Item boost_chestplate;
	public static Item boost_leggings;
	public static Item boost_boots;
	public static Item cannabis_leaf;
	public static Item cannabis_cooked_leaf;
	public static Item join;
	public static Item cannabis_seed;
	
	//CHRISTMAS UPDATE
	public static final ArmorMaterial turtlearmor = EnumHelper.addArmorMaterial("turtlearmor", References.MODID + ":turtlearmor", 130, new int[] {4, 6, 6, 4}, 20, SoundEvents.ITEM_ARMOR_EQUIP_DIAMOND, 3.0F);
	public static final ArmorMaterial christmas = EnumHelper.addArmorMaterial("christmas", References.MODID + ":christmas", 190, new int[] {6, 8, 8, 6}, 20, SoundEvents.ITEM_ARMOR_EQUIP_DIAMOND, 3.0F);
	public static Item christmas_helmet;
	public static Item christmas_chestplate;
	public static Item christmas_leggings;
	public static Item christmas_boots;
	public static Item candy_cane;
	public static Item turtle_helmet;
	public static Item xp_berry;
	
	public static void init() 
	{
		xp_berry = new XpBerry("xp_berry");
		candy_cane = new ItemFoodBase("candy_cane", 3, 3, false);
		christmas_helmet = new EmeraldHelmet("christmas_helmet", christmas, 1, EntityEquipmentSlot.HEAD);
		christmas_chestplate = new EmeraldHelmet("christmas_chestplate", christmas, 1, EntityEquipmentSlot.CHEST);
		christmas_leggings = new EmeraldHelmet("christmas_leggings", christmas, 1, EntityEquipmentSlot.LEGS);
		christmas_boots = new EmeraldHelmet("christmas_boots", christmas, 1, EntityEquipmentSlot.FEET);
		turtle_helmet = new TurtleHelmet("turtle_helmet", turtlearmor, 1, EntityEquipmentSlot.HEAD);
		uranium_ingot = new ItemUraniumIngot("uranium_ingot");
		fromage = new ItemFoodBase("fromage", 4, 4, false);
		cannabis_leaf = new ItemBase("cannabis_leaf");
		cannabis_cooked_leaf = new ItemBase("cannabis_cooked_leaf");
		join = new ItemJoin("join", 2, 2, false);
		cannabis_seed = new ItemSeeds(BlocksMod.cannabis_crop, Blocks.FARMLAND).setUnlocalizedName("cannabis_seed").setCreativeTab(Drunly.drunlyfarm).setRegistryName("cannabis_seed");
		boost_helmet = new BoostHelmet("boost_helmet", boostarmor, 1, EntityEquipmentSlot.HEAD);
		boost_chestplate = new BoostChestplate("boost_chestplate", boostarmor, 1, EntityEquipmentSlot.CHEST);
		boost_leggings = new BoostLeggings("boost_leggings", boostarmor, 1, EntityEquipmentSlot.LEGS);
		boost_boots = new BoostBoots("boost_boots", boostarmor, 1, EntityEquipmentSlot.FEET);
		farmtool = new FarmTool(toolmulti).setCreativeTab(Drunly.drunlytab).setUnlocalizedName("farmtool").setRegistryName("farmtool");
		drunlyk_ring = new ItemDrunlykRing("drunlyk_ring");
		hematite_ring = new ItemHematiteRing("hematite_ring");
		emerald_bow = new EmeraldBow("emerald_bow");
		rubis_bow = new RubisBow("rubis_bow");
		cobalt_bow = new CobaltBow("cobalt_bow");
		citron_ice = new ItemCitronIce("citron_ice", 2, 2, false);
		myrtille_ice = new ItemMyrtilleIce("myrtille_ice", 2, 2, false);
		cerise_ice = new ItemCeriseIce("cerise_ice", 2, 2, false);
		kiwi_ice = new ItemKiwiIce("kiwi_ice", 2, 2, false);
		fraise_ice = new ItemFraiseIce("fraise_ice", 2, 2, false);
		courgette_modifier = new FarmingModifier("courgette_modifier");
		courgette_seed_planter = new CourgetteSeedPlanter(toolseedplanter).setRegistryName("courgette_seed_planter").setUnlocalizedName("courgette_seed_planter").setCreativeTab(Drunly.drunlyfarm);
		riz_modifier = new FarmingModifier("riz_modifier");
		tomato_modifier = new FarmingModifier("tomato_modifier");
		citron_modifier = new FarmingModifier("citron_modifier");
		myrtille_modifier = new FarmingModifier("myrtille_modifier");
		salade_modifier = new FarmingModifier("salade_modifier");
		courgette_modifier = new FarmingModifier("courgette_modifier");
		salade_modifier = new FarmingModifier("salade_modifier");
		riz_seed_planter = new RizSeedPlanter(toolseedplanter).setRegistryName("riz_seed_planter").setUnlocalizedName("riz_seed_planter").setCreativeTab(Drunly.drunlyfarm);
		tomato_seed_planter = new TomatoSeedPlanter(toolseedplanter).setRegistryName("tomato_seed_planter").setUnlocalizedName("tomato_seed_planter").setCreativeTab(Drunly.drunlyfarm);
		citron_seed_planter = new CitronSeedPlanter(toolseedplanter).setRegistryName("citron_seed_planter").setUnlocalizedName("citron_seed_planter").setCreativeTab(Drunly.drunlyfarm);
		salade_seed_planter = new SaladeSeedPlanter(toolseedplanter).setRegistryName("salade_seed_planter").setUnlocalizedName("salade_seed_planter").setCreativeTab(Drunly.drunlyfarm);
		myrtille_seed_planter = new MyrtilleSeedPlanter(toolseedplanter).setRegistryName("myrtille_seed_planter").setUnlocalizedName("myrtille_seed_planter").setCreativeTab(Drunly.drunlyfarm);
		admin_sword = new HematiteSword(tooladmin).setRegistryName("admin_sword").setUnlocalizedName("admin_sword").setCreativeTab(Drunly.drunlytab);
		salade_tomate = new SaladeTomate("salade_tomate", 4, 4, false);
		risotto = new Risotto("risotto", 5, 5, false);
		hardened_briquet = new HardenedBriquet("hardened_briquet");
		drunlyk_hammer = new DrunlykHammer(tooldrunlyk).setRegistryName("drunlyk_hammer").setUnlocalizedName("drunlyk_hammer").setCreativeTab(Drunly.drunlytab);
		courgette_seed = new ItemSeeds(BlocksMod.courgette_crop, Blocks.FARMLAND).setUnlocalizedName("courgette_seed").setCreativeTab(Drunly.drunlyfarm).setRegistryName("courgette_seed");
		courgette = new Tomato("courgette", 3, 3, false);
		tomato_seed = new ItemSeeds(BlocksMod.tomato_crop, Blocks.FARMLAND).setUnlocalizedName("tomato_seed").setCreativeTab(Drunly.drunlyfarm).setRegistryName("tomato_seed");
		tomato = new Tomato("tomato", 3, 3, false);
		myrtille_seed = new ItemSeeds(BlocksMod.myrtille_crop, Blocks.FARMLAND).setUnlocalizedName("myrtille_seed").setCreativeTab(Drunly.drunlyfarm).setRegistryName("myrtille_seed");
		myrtille = new Tomato("myrtille", 3, 3, false);
		citron_seed = new ItemSeeds(BlocksMod.citron_crop, Blocks.FARMLAND).setUnlocalizedName("citron_seed").setCreativeTab(Drunly.drunlyfarm).setRegistryName("citron_seed");
		citron = new Tomato("citron", 3, 3, false);
		salade_seed = new ItemSeeds(BlocksMod.salade_crop, Blocks.FARMLAND).setUnlocalizedName("salade_seed").setCreativeTab(Drunly.drunlyfarm).setRegistryName("salade_seed");
		salade = new Tomato("salade", 3, 3, false);
		riz_seed = new ItemSeeds(BlocksMod.riz_crop, Blocks.FARMLAND).setUnlocalizedName("riz_seed").setCreativeTab(Drunly.drunlyfarm).setRegistryName("riz_seed");
		riz = new Tomato("riz", 3, 3, false);
		cerise = new Cerise("cerise", 3, 3, false);
		grenade = new Grenade("grenade", 3, 3, false);
		hematite_helmet = new HematiteHelmet("hematite_helmet", hematitearmor, 1, EntityEquipmentSlot.HEAD);
		hematite_chestplate = new HematiteChestplate("hematite_chestplate", hematitearmor, 1, EntityEquipmentSlot.CHEST);
		hematite_leggings = new HematiteLeggings("hematite_leggings", hematitearmor, 1, EntityEquipmentSlot.LEGS);
		hematite_boots = new HematiteBoots("hematite_boots", hematitearmor, 1, EntityEquipmentSlot.FEET);
		hematite_sword = new HematiteSword(toolhematite).setRegistryName("hematite_sword").setUnlocalizedName("hematite_sword").setCreativeTab(Drunly.drunlytab);
		hematite_pickaxe = new HematitePickaxe(toolhematite).setRegistryName("hematite_pickaxe").setUnlocalizedName("hematite_pickaxe").setCreativeTab(Drunly.drunlytab);
		hematite_axe = new HematiteAxe(toolhematite).setRegistryName("hematite_axe").setUnlocalizedName("hematite_axe").setCreativeTab(Drunly.drunlytab);
		hematite_shovel = new HematiteShovel(toolhematite).setRegistryName("hematite_shovel").setUnlocalizedName("hematite_shovel").setCreativeTab(Drunly.drunlytab);
		hematite_ingot = new HematiteIngot("hematite_ingot");
		hematite_hammer = new HematiteHammer(toolhematite).setRegistryName("hematite_hammer").setUnlocalizedName("hematite_hammer").setCreativeTab(Drunly.drunlytab);
		hardened_coal = new HardenedCoal("hardened_coal");
		coins = new Coins("coins");
		gold_stick = new GoldStick("gold_stick");
		erable_potion = new ErablePotion("erable_potion", 1, 1, false);
		empty_modifier = new FarmingModifier("empty_modifier");
		potato_modifier = new FarmingModifier("potato_modifier");
		carrot_modifier = new FarmingModifier("carrot_modifier");
		strawberry_modifier = new FarmingModifier("strawberry_modifier");
		kiwi_modifier = new FarmingModifier("kiwi_modifier");
		erable_modifier = new FarmingModifier("erable_modifier");
		trefle_modifier = new FarmingModifier("trefle_modifier");
		empty_seed_planter = new EmptySeedPlanter("empty_seed_planter");
		potato_seed_planter = new PotatoSeedPlanter(toolseedplanter).setRegistryName("potato_seed_planter").setUnlocalizedName("potato_seed_planter").setCreativeTab(Drunly.drunlyfarm);
		carrot_seed_planter = new CarrotSeedPlanter(toolseedplanter).setRegistryName("carrot_seed_planter").setUnlocalizedName("carrot_seed_planter").setCreativeTab(Drunly.drunlyfarm);
		strawberry_seed_planter = new StrawberrySeedPlanter(toolseedplanter).setRegistryName("strawberry_seed_planter").setUnlocalizedName("strawberry_seed_planter").setCreativeTab(Drunly.drunlyfarm);
		kiwi_seed_planter = new KiwiSeedPlanter(toolseedplanter).setRegistryName("kiwi_seed_planter").setUnlocalizedName("kiwi_seed_planter").setCreativeTab(Drunly.drunlyfarm);
		erable_seed_planter = new ErableSeedPlanter(toolseedplanter).setRegistryName("erable_seed_planter").setUnlocalizedName("erable_seed_planter").setCreativeTab(Drunly.drunlyfarm);
		trefle_seed_planter = new TrefleSeedPlanter(toolseedplanter).setRegistryName("trefle_seed_planter").setUnlocalizedName("trefle_seed_planter").setCreativeTab(Drunly.drunlyfarm);
		drunlyk_helmet = new DrunlykHelmet("drunlyk_helmet", drunlykarmor, 1, EntityEquipmentSlot.HEAD);
		drunlyk_chestplate = new DrunlykChestplate("drunlyk_chestplate", drunlykarmor, 1, EntityEquipmentSlot.CHEST);
		drunlyk_leggings = new DrunlykLeggings("drunlyk_leggings", drunlykarmor, 1, EntityEquipmentSlot.LEGS);
		drunlyk_boots = new DrunlykBoots("drunlyk_boots", drunlykarmor, 1, EntityEquipmentSlot.FEET);
		drunlyk_sword = new DrunlykSword(tooldrunlyk).setRegistryName("drunlyk_sword").setUnlocalizedName("drunlyk_sword").setCreativeTab(Drunly.drunlytab);
		drunlyk_pickaxe = new DrunlykPickaxe(tooldrunlyk).setRegistryName("drunlyk_pickaxe").setUnlocalizedName("drunlyk_pickaxe").setCreativeTab(Drunly.drunlytab);
		drunlyk_axe = new DrunlykAxe(tooldrunlyk).setRegistryName("drunlyk_axe").setUnlocalizedName("drunlyk_axe").setCreativeTab(Drunly.drunlytab);
		drunlyk_shovel = new DrunlykShovel(tooldrunlyk).setRegistryName("drunlyk_shovel").setUnlocalizedName("drunlyk_shovel").setCreativeTab(Drunly.drunlytab);
		vodka = new Vodka("vodka", 1, 1, false);
		beer = new Beer("beer", 3, 3, false);
		fried_egg = new FriedEgg("fried_egg", 3, 3, false);
		money = new Money("money");
		rubis_hoe = new RubisHoe(toolrubis ,"rubis_hoe");
		emerald_hoe = new EmeraldHoe(toolemerald, "emerald_hoe");
		cobalt_hoe = new CobaltHoe(toolcobalt, "cobalt_hoe");
		drunlyk_hoe = new DrunlykHoe(tooldrunlyk, "drunlyk_hoe");
		hematite_hoe = new HematiteHoe(toolhematite, "hematite_hoe");
		magical_recolter = new MagicalRecolter(toolrubis, "magical_recolter");
		stone_hammer = new StoneHammer(toolstonehammer).setRegistryName("stone_hammer").setUnlocalizedName("stone_hammer").setCreativeTab(Drunly.drunlytab);
		iron_hammer = new IronHammer(toolironhammer).setRegistryName("iron_hammer").setUnlocalizedName("iron_hammer").setCreativeTab(Drunly.drunlytab);
		gold_hammer = new GoldHammer(toolgoldhammer).setRegistryName("gold_hammer").setUnlocalizedName("gold_hammer").setCreativeTab(Drunly.drunlytab);
		diamond_hammer = new DiamondHammer(tooldiamondhammer).setRegistryName("diamond_hammer").setUnlocalizedName("diamond_hammer").setCreativeTab(Drunly.drunlytab);
		emerald_hammer = new EmeraldHammer(toolemerald).setRegistryName("emerald_hammer").setUnlocalizedName("emerald_hammer").setCreativeTab(Drunly.drunlytab);
		rubis_hammer = new RubisHammer(toolrubis).setRegistryName("rubis_hammer").setUnlocalizedName("rubis_hammer").setCreativeTab(Drunly.drunlytab);
		cobalt_hammer = new CobaltHammer(toolcobalt).setRegistryName("cobalt_hammer").setUnlocalizedName("cobalt_hammer").setCreativeTab(Drunly.drunlytab);
		fraise_seed = new ItemSeeds(BlocksMod.fraisecrop, Blocks.FARMLAND).setUnlocalizedName("fraise_seed").setCreativeTab(Drunly.drunlyfarm).setRegistryName("fraise_seed");
		erable_seed = new ItemSeeds(BlocksMod.erablecrop, Blocks.FARMLAND).setUnlocalizedName("erable_seed").setCreativeTab(Drunly.drunlyfarm).setRegistryName("erable_seed");
		kiwi_seed = new ItemSeeds(BlocksMod.kiwicrop, Blocks.FARMLAND).setUnlocalizedName("kiwi_seed").setCreativeTab(Drunly.drunlyfarm).setRegistryName("kiwi_seed");
		trefle_seed = new ItemSeeds(BlocksMod.treflecrop, Blocks.FARMLAND).setUnlocalizedName("trefle_seed").setCreativeTab(Drunly.drunlyfarm).setRegistryName("trefle_seed");
		fraise = new FraiseFood("fraise", 2, 2, false);
		erable = new ErableFood("erable", 2, 2, false);
		kiwi = new KiwiFood("kiwi", 2, 2, false);
		trefle = new TrefleFood("trefle", 2, 2, false);
		hardened_pickaxe = new HardenedPickaxe(toolhardened).setRegistryName("hardened_pickaxe").setUnlocalizedName("hardened_pickaxe").setCreativeTab(Drunly.drunlytab);
		dynamite = new Dynamite("dynamite");
		hardened_dynamite = new HardenedDynamite("hardened_dynamite");
		emerald_helmet = new EmeraldHelmet("emerald_helmet", emeraldarmor, 1, EntityEquipmentSlot.HEAD);
		emerald_chestplate = new EmeraldChestplate("emerald_chestplate", emeraldarmor, 1, EntityEquipmentSlot.CHEST);
		emerald_leggings = new EmeraldLeggings("emerald_leggings", emeraldarmor, 1, EntityEquipmentSlot.LEGS);
		emerald_boots = new EmeraldBoots("emerald_boots", emeraldarmor, 1, EntityEquipmentSlot.FEET);
		emerald_sword = new EmeraldSword(toolemerald).setRegistryName("emerald_sword").setUnlocalizedName("emerald_sword").setCreativeTab(Drunly.drunlytab);
		emerald_pickaxe = new EmeraldPickaxe(toolemerald).setRegistryName("emerald_pickaxe").setUnlocalizedName("emerald_pickaxe").setCreativeTab(Drunly.drunlytab);
		emerald_axe = new EmeraldAxe(toolemerald).setRegistryName("emerald_axe").setUnlocalizedName("emerald_axe").setCreativeTab(Drunly.drunlytab);
		emerald_shovel = new EmeraldShovel(toolemerald).setRegistryName("emerald_shovel").setUnlocalizedName("emerald_shovel").setCreativeTab(Drunly.drunlytab);
		rubis_helmet = new RubisHelmet("rubis_helmet", rubisarmor, 1, EntityEquipmentSlot.HEAD);
		rubis_chestplate = new RubisChestplate("rubis_chestplate", rubisarmor, 1, EntityEquipmentSlot.CHEST);
		rubis_leggings = new RubisLeggings("rubis_leggings", rubisarmor, 1, EntityEquipmentSlot.LEGS);
		rubis_boots = new RubisBoots("rubis_boots", rubisarmor, 1, EntityEquipmentSlot.FEET);
		rubis_sword = new RubisSword(toolrubis).setRegistryName("rubis_sword").setUnlocalizedName("rubis_sword").setCreativeTab(Drunly.drunlytab);
		rubis_pickaxe = new RubisPickaxe(toolrubis).setRegistryName("rubis_pickaxe").setUnlocalizedName("rubis_pickaxe").setCreativeTab(Drunly.drunlytab);
		rubis_axe = new RubisAxe(toolrubis).setRegistryName("rubis_axe").setUnlocalizedName("rubis_axe").setCreativeTab(Drunly.drunlytab);
		rubis_shovel = new RubisShovel(toolrubis).setRegistryName("rubis_shovel").setUnlocalizedName("rubis_shovel").setCreativeTab(Drunly.drunlytab);
		rubis_ingot = new RubisIngot("rubis_ingot");
		rubis_apple = new RubisApple("rubis_apple", 3, 3, false);
		cobalt_helmet = new CobaltHelmet("cobalt_helmet", cobaltarmor, 1, EntityEquipmentSlot.HEAD);
		cobalt_chestplate = new CobaltChestplate("cobalt_chestplate", cobaltarmor, 1, EntityEquipmentSlot.CHEST);
		cobalt_leggings = new CobaltLeggings("cobalt_leggings", cobaltarmor, 1, EntityEquipmentSlot.LEGS);
		cobalt_boots = new CobaltBoots("cobalt_boots", cobaltarmor, 1, EntityEquipmentSlot.FEET);
		cobalt_sword = new CobaltSword(toolcobalt).setRegistryName("cobalt_sword").setUnlocalizedName("cobalt_sword").setCreativeTab(Drunly.drunlytab);
		cobalt_pickaxe = new CobaltPickaxe(toolcobalt).setRegistryName("cobalt_pickaxe").setUnlocalizedName("cobalt_pickaxe").setCreativeTab(Drunly.drunlytab);
		cobalt_axe = new CobaltAxe(toolcobalt).setRegistryName("cobalt_axe").setUnlocalizedName("cobalt_axe").setCreativeTab(Drunly.drunlytab);
		cobalt_shovel = new CobaltShovel(toolcobalt).setRegistryName("cobalt_shovel").setUnlocalizedName("cobalt_shovel").setCreativeTab(Drunly.drunlytab);
		cobalt_ingot = new CobaltIngot("cobalt_ingot");
		cobalt_apple = new CobaltApple("cobalt_apple", 3, 3, false); 
		drunlyk_ingot = new DrunlykIngot("drunlyk_ingot");
		drunlyk_powder = new DrunlykPowder("drunlyk_powder");
		acier = new Acier("acier");
		key = new ItemBase("key");
	}
	
	@SubscribeEvent
	public static void registerItems(RegistryEvent.Register<Item> event)  

	{
		event.getRegistry().registerAll(xp_berry);

		event.getRegistry().registerAll(turtle_helmet);
		event.getRegistry().registerAll(christmas_boots);
		event.getRegistry().registerAll(christmas_chestplate);
		event.getRegistry().registerAll(christmas_helmet);
		event.getRegistry().registerAll(christmas_leggings);
		event.getRegistry().registerAll(candy_cane);
		event.getRegistry().registerAll(uranium_ingot);
		event.getRegistry().registerAll(fromage);
		event.getRegistry().registerAll(cannabis_leaf);
		event.getRegistry().registerAll(cannabis_cooked_leaf);
		event.getRegistry().registerAll(join);
		event.getRegistry().registerAll(cannabis_seed);
		event.getRegistry().registerAll(boost_helmet);
		event.getRegistry().registerAll(boost_chestplate);
		event.getRegistry().registerAll(boost_leggings);
		event.getRegistry().registerAll(boost_boots);
		event.getRegistry().registerAll(hematite_ring);
		event.getRegistry().registerAll(drunlyk_ring);
		event.getRegistry().registerAll(emerald_bow);
		event.getRegistry().registerAll(rubis_bow);
		event.getRegistry().registerAll(cobalt_bow);
		event.getRegistry().registerAll(citron_ice);
		event.getRegistry().registerAll(myrtille_ice);
		event.getRegistry().registerAll(cerise_ice);
		event.getRegistry().registerAll(kiwi_ice);
		event.getRegistry().registerAll(fraise_ice);
		event.getRegistry().registerAll(salade_seed_planter);
		event.getRegistry().registerAll(salade_modifier);
		event.getRegistry().registerAll(myrtille_seed_planter);
		event.getRegistry().registerAll(myrtille_modifier);
		event.getRegistry().registerAll(tomato_seed_planter);
		event.getRegistry().registerAll(tomato_modifier);
		event.getRegistry().registerAll(courgette_seed_planter);
		event.getRegistry().registerAll(courgette_modifier);
		event.getRegistry().registerAll(riz_seed_planter);
		event.getRegistry().registerAll(riz_modifier);
		event.getRegistry().registerAll(citron_seed_planter);
		event.getRegistry().registerAll(citron_modifier);
		event.getRegistry().registerAll(admin_sword);
		event.getRegistry().registerAll(salade_tomate);
		event.getRegistry().registerAll(risotto);
		event.getRegistry().registerAll(hardened_briquet);
		event.getRegistry().registerAll(drunlyk_hammer);
		event.getRegistry().registerAll(courgette);
		event.getRegistry().registerAll(courgette_seed);
		event.getRegistry().registerAll(riz_seed);
		event.getRegistry().registerAll(riz);
		event.getRegistry().registerAll(myrtille);
		event.getRegistry().registerAll(myrtille_seed);
		event.getRegistry().registerAll(salade);
		event.getRegistry().registerAll(salade_seed);
		event.getRegistry().registerAll(citron);
		event.getRegistry().registerAll(citron_seed);
		event.getRegistry().registerAll(cerise);
		event.getRegistry().registerAll(grenade);
		event.getRegistry().registerAll(tomato);
		event.getRegistry().registerAll(tomato_seed);
		event.getRegistry().registerAll(emerald_hoe);
		event.getRegistry().registerAll(cobalt_hoe);
		event.getRegistry().registerAll(drunlyk_hoe);
		event.getRegistry().registerAll(hematite_hoe);
		event.getRegistry().registerAll(hematite_ingot);
		event.getRegistry().registerAll(hematite_hammer);
		event.getRegistry().registerAll(hematite_helmet);
		event.getRegistry().registerAll(hematite_chestplate);
		event.getRegistry().registerAll(hematite_leggings);
		event.getRegistry().registerAll(hematite_boots);
		event.getRegistry().registerAll(hematite_sword);
		event.getRegistry().registerAll(hematite_pickaxe);
		event.getRegistry().registerAll(hematite_axe);
		event.getRegistry().registerAll(hematite_shovel);
		event.getRegistry().registerAll(gold_stick);
		event.getRegistry().registerAll(drunlyk_helmet);
		event.getRegistry().registerAll(drunlyk_chestplate);
		event.getRegistry().registerAll(drunlyk_leggings);
		event.getRegistry().registerAll(drunlyk_boots);
		event.getRegistry().registerAll(drunlyk_sword);
		event.getRegistry().registerAll(drunlyk_pickaxe);
		event.getRegistry().registerAll(drunlyk_axe);
		event.getRegistry().registerAll(drunlyk_shovel);
		event.getRegistry().registerAll(hardened_coal);
		event.getRegistry().registerAll(coins);
		event.getRegistry().registerAll(erable_potion);
		event.getRegistry().registerAll(acier);
		event.getRegistry().registerAll(empty_seed_planter);
		event.getRegistry().registerAll(potato_seed_planter);
		event.getRegistry().registerAll(carrot_seed_planter);
		event.getRegistry().registerAll(strawberry_seed_planter);
		event.getRegistry().registerAll(kiwi_seed_planter);
		event.getRegistry().registerAll(erable_seed_planter);
		event.getRegistry().registerAll(trefle_seed_planter);	
		event.getRegistry().registerAll(empty_modifier);
		event.getRegistry().registerAll(potato_modifier);
		event.getRegistry().registerAll(carrot_modifier);
		event.getRegistry().registerAll(strawberry_modifier);
		event.getRegistry().registerAll(kiwi_modifier);
		event.getRegistry().registerAll(erable_modifier);
		event.getRegistry().registerAll(trefle_modifier);
		event.getRegistry().registerAll(drunlyk_ingot);
		event.getRegistry().registerAll(drunlyk_powder);
		event.getRegistry().registerAll(magical_recolter);
		event.getRegistry().registerAll(rubis_hoe);
		event.getRegistry().registerAll(beer);
		event.getRegistry().registerAll(hardened_pickaxe);
		event.getRegistry().registerAll(money);
		event.getRegistry().registerAll(fraise_seed);
		event.getRegistry().registerAll(dynamite);
		event.getRegistry().registerAll(hardened_dynamite);
		event.getRegistry().registerAll(fraise);
		event.getRegistry().registerAll(emerald_helmet);
		event.getRegistry().registerAll(emerald_chestplate);
		event.getRegistry().registerAll(emerald_leggings);
		event.getRegistry().registerAll(emerald_boots);
		event.getRegistry().registerAll(erable_seed);
		event.getRegistry().registerAll(erable);
		event.getRegistry().registerAll(kiwi_seed);
		event.getRegistry().registerAll(kiwi);
		event.getRegistry().registerAll(trefle_seed);
		event.getRegistry().registerAll(trefle);
		event.getRegistry().registerAll(emerald_sword);
		event.getRegistry().registerAll(emerald_pickaxe);
		event.getRegistry().registerAll(emerald_axe);
		event.getRegistry().registerAll(emerald_shovel);	
		event.getRegistry().registerAll(rubis_helmet);
		event.getRegistry().registerAll(rubis_chestplate);
		event.getRegistry().registerAll(rubis_leggings);
		event.getRegistry().registerAll(rubis_boots);
		event.getRegistry().registerAll(rubis_sword);
		event.getRegistry().registerAll(rubis_pickaxe);
		event.getRegistry().registerAll(rubis_axe);
		event.getRegistry().registerAll(rubis_shovel);
		event.getRegistry().registerAll(rubis_ingot);
		event.getRegistry().registerAll(rubis_apple); 
		event.getRegistry().registerAll(cobalt_helmet);
		event.getRegistry().registerAll(cobalt_chestplate);
		event.getRegistry().registerAll(cobalt_leggings);
		event.getRegistry().registerAll(cobalt_boots);
		event.getRegistry().registerAll(cobalt_sword);
		event.getRegistry().registerAll(cobalt_pickaxe);
		event.getRegistry().registerAll(cobalt_axe);
		event.getRegistry().registerAll(cobalt_shovel);
		event.getRegistry().registerAll(cobalt_ingot);
		event.getRegistry().registerAll(cobalt_apple);
		event.getRegistry().registerAll(fried_egg);
		event.getRegistry().registerAll(vodka);
		event.getRegistry().registerAll(stone_hammer);
		event.getRegistry().registerAll(iron_hammer);
		event.getRegistry().registerAll(gold_hammer);
		event.getRegistry().registerAll(diamond_hammer);
		event.getRegistry().registerAll(emerald_hammer);
		event.getRegistry().registerAll(rubis_hammer);
		event.getRegistry().registerAll(cobalt_hammer);
		event.getRegistry().registerAll(key);
		event.getRegistry().registerAll(farmtool);
	}
	
	@SubscribeEvent
	public static void registerRenders(ModelRegistryEvent event)
	{
		registerRender(xp_berry);

		registerRender(turtle_helmet);
		registerRender(christmas_boots);
		registerRender(christmas_chestplate);
		registerRender(christmas_helmet);
		registerRender(christmas_leggings);
		registerRender(candy_cane);
		registerRender(uranium_ingot);
		registerRender(fromage);
		registerRender(cannabis_leaf);
		registerRender(cannabis_cooked_leaf);
		registerRender(join);
		registerRender(boost_helmet);
		registerRender(boost_chestplate);
		registerRender(boost_leggings);
		registerRender(boost_boots);
		registerRender(cannabis_seed);
		registerRender(key);
		registerRender(drunlyk_ring);
		registerRender(hematite_ring);
		registerRender(emerald_bow);
		registerRender(rubis_bow);
		registerRender(cobalt_bow);
		registerRender(cerise_ice);
		registerRender(fraise_ice);
		registerRender(citron_ice);
		registerRender(kiwi_ice);
		registerRender(myrtille_ice);
		registerRender(salade_seed_planter);
		registerRender(salade_modifier);
		registerRender(myrtille_seed_planter);
		registerRender(myrtille_modifier);
		registerRender(tomato_seed_planter);
		registerRender(tomato_modifier);
		registerRender(courgette_seed_planter);
		registerRender(courgette_modifier);
		registerRender(riz_seed_planter);
		registerRender(riz_modifier);
		registerRender(citron_modifier);
		registerRender(citron_seed_planter);
		registerRender(admin_sword);
		registerRender(salade_tomate);
		registerRender(risotto);
		registerRender(drunlyk_hammer);
		registerRender(hardened_briquet);
		registerRender(courgette);
		registerRender(courgette_seed);
		registerRender(cerise);
		registerRender(grenade);
		registerRender(citron);
		registerRender(citron_seed);
		registerRender(myrtille);
		registerRender(myrtille_seed);
		registerRender(riz);
		registerRender(riz_seed);
		registerRender(salade);
		registerRender(salade_seed);
		registerRender(tomato);
		registerRender(tomato_seed);
		registerRender(gold_stick);
		registerRender(hematite_hammer);
		registerRender(emerald_hoe);
		registerRender(hematite_ingot);
		registerRender(cobalt_hoe);
		registerRender(drunlyk_hoe);
		registerRender(hematite_hoe);
		registerRender(hematite_helmet);
		registerRender(hematite_chestplate);
		registerRender(hematite_leggings);
		registerRender(hematite_boots);	
		registerRender(hematite_sword);
		registerRender(hematite_pickaxe);
		registerRender(hematite_axe);
		registerRender(hematite_shovel);
		registerRender(drunlyk_helmet);
		registerRender(drunlyk_chestplate);
		registerRender(drunlyk_leggings);
		registerRender(drunlyk_boots);	
		registerRender(drunlyk_sword);
		registerRender(drunlyk_pickaxe);
		registerRender(drunlyk_axe);
		registerRender(drunlyk_shovel);
		registerRender(hardened_coal);
		registerRender(coins);
		registerRender(erable_potion);
		registerRender(acier);
		registerRender(empty_seed_planter);
		registerRender(potato_seed_planter);
		registerRender(carrot_seed_planter);
		registerRender(strawberry_seed_planter);
		registerRender(erable_seed_planter);
		registerRender(kiwi_seed_planter);
		registerRender(trefle_seed_planter);
		registerRender(empty_modifier);
		registerRender(potato_modifier);
		registerRender(carrot_modifier);
		registerRender(strawberry_modifier);
		registerRender(erable_modifier);
		registerRender(kiwi_modifier);
		registerRender(trefle_modifier);
		registerRender(drunlyk_powder);
		registerRender(drunlyk_ingot);
		registerRender(magical_recolter);
		registerRender(stone_hammer);
		registerRender(rubis_hoe);
		registerRender(iron_hammer);
		registerRender(gold_hammer);
		registerRender(diamond_hammer);
		registerRender(emerald_hammer);
		registerRender(rubis_hammer);
		registerRender(cobalt_hammer);		
		registerRender(vodka);
		registerRender(beer);
		registerRender(hardened_pickaxe);
		registerRender(money);
		registerRender(fraise_seed);
		registerRender(dynamite);
		registerRender(hardened_dynamite);
		registerRender(fraise);
		registerRender(erable);
		registerRender(erable_seed);
		registerRender(kiwi);
		registerRender(kiwi_seed);
		registerRender(trefle);
		registerRender(rubis_ingot);
		registerRender(trefle_seed);	
		registerRender(emerald_helmet);
		registerRender(emerald_chestplate);
		registerRender(emerald_leggings);
		registerRender(emerald_boots);	
		registerRender(emerald_sword);
		registerRender(emerald_pickaxe);
		registerRender(emerald_axe);
		registerRender(emerald_shovel);
		registerRender(rubis_helmet);
		registerRender(rubis_chestplate);
		registerRender(rubis_leggings);
		registerRender(rubis_boots);
		registerRender(rubis_sword);
		registerRender(rubis_pickaxe);
		registerRender(rubis_axe);
		registerRender(rubis_shovel);
		registerRender(rubis_apple); 
		registerRender(cobalt_helmet);
		registerRender(cobalt_chestplate);
		registerRender(cobalt_leggings);
		registerRender(cobalt_boots);
		registerRender(cobalt_ingot);
		registerRender(cobalt_sword);
		registerRender(cobalt_pickaxe);
		registerRender(cobalt_axe);
		registerRender(cobalt_shovel);
		registerRender(cobalt_apple);
		registerRender(fried_egg);
		registerRender(farmtool);
	}
	
	private static void registerRender(Item item)
	{
		ModelLoader.setCustomModelResourceLocation(item, 0, new ModelResourceLocation(item.getRegistryName(), "isuperarmorentory"));
	}
}
